/*
 * Authentication API
 * This Authentication API allows you to get the authentication information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CorporateSystemsSaoCarlos@br.experian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.serasa.common.utils.model.athenas;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import javax.validation.constraints.*;

/**
 * The authentication information
 */
@ApiModel(description = "The authentication information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-13T11:22:34.856-03:00")
public class AuthenticationInfo   {
  @JsonProperty("documentBase")
  private String documentBase = null;

  @JsonProperty("logon")
  private String logon = null;

  @JsonProperty("expiration")
  private Date expiration = null;

  public AuthenticationInfo documentBase(String documentBase) {
    this.documentBase = documentBase;
    return this;
  }

  /**
   * Unique number to identify the customer
   * @return documentBase
   **/
  @JsonProperty("documentBase")
  @ApiModelProperty(value = "Unique number to identify the customer")
  public String getDocumentBase() {
    return documentBase;
  }

  public void setDocumentBase(String documentBase) {
    this.documentBase = documentBase;
  }

  public AuthenticationInfo logon(String logon) {
    this.logon = logon;
    return this;
  }

  /**
   * The user name
   * @return logon
   **/
  @JsonProperty("logon")
  @ApiModelProperty(value = "The user name")
  public String getLogon() {
    return logon;
  }

  public void setLogon(String logon) {
    this.logon = logon;
  }

  public AuthenticationInfo expiration(Date expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * Remaining time for the session to expire
   * @return expiration
   **/
  @JsonProperty("expiration")
  @ApiModelProperty(value = "Remaining time for the session to expire")
  public Date getExpiration() {
    return expiration;
  }

  public void setExpiration(Date expiration) {
    this.expiration = expiration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationInfo authenticationInfo = (AuthenticationInfo) o;
    return Objects.equals(this.documentBase, authenticationInfo.documentBase) &&
        Objects.equals(this.logon, authenticationInfo.logon) &&
        Objects.equals(this.expiration, authenticationInfo.expiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentBase, logon, expiration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationInfo {\n");
    
    sb.append("    documentBase: ").append(toIndentedString(documentBase)).append("\n");
    sb.append("    logon: ").append(toIndentedString(logon)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

