/*
 * Customer API
 * This Customer API allows you to get informations about the customer from user.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CorporateSystemsSaoCarlos@br.experian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.serasa.common.utils.model.athenas;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Information about the customer document and trading name
 */
@ApiModel(description = "Information about the customer document and trading name")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-30T14:15:56.653-03:00")
public class Customer   {
  @JsonProperty("tradingName")
  private String tradingName = null;

  @JsonProperty("document")
  private String document = null;

  public Customer tradingName(String tradingName) {
    this.tradingName = tradingName;
    return this;
  }

  /**
   * Customer trading name
   * @return tradingName
   **/
  @JsonProperty("tradingName")
  @ApiModelProperty(value = "Customer trading name")
  public String getTradingName() {
    return tradingName;
  }

  public void setTradingName(String tradingName) {
    this.tradingName = tradingName;
  }

  public Customer document(String document) {
    this.document = document;
    return this;
  }

  /**
   * Number that identify the customer
   * @return document
   **/
  @JsonProperty("document")
  @ApiModelProperty(value = "Number that identify the customer")
  public String getDocument() {
    return document;
  }

  public void setDocument(String document) {
    this.document = document;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.tradingName, customer.tradingName) &&
        Objects.equals(this.document, customer.document);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradingName, document);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    tradingName: ").append(toIndentedString(tradingName)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

