/*
 * Invoice API
 * This Invoice API allows you to get informations about invoices.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CorporateSystemsSaoCarlos@br.experian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.serasa.common.utils.model.athenas;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import javax.validation.constraints.*;

/**
 * Information about the invoice value and due date
 */
@ApiModel(description = "Information about the invoice value and due date")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-02T11:46:37.783-03:00")
public class Invoice   {
  @JsonProperty("dueDate")
  private Date dueDate = null;

  @JsonProperty("value")
  private Float value = null;

  @JsonProperty("contractNumber")
  private String contractNumber = null;

  @JsonProperty("nfeNumber")
  private String nfeNumber = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("emissionDate")
  private Date emissionDate = null;

  public Invoice dueDate(Date dueDate) {
    this.dueDate = dueDate;
    return this;
  }

  /**
   * Invoice due date
   * @return dueDate
   **/
  @JsonProperty("dueDate")
  @ApiModelProperty(value = "Invoice due date")
  public Date getDueDate() {
    return dueDate;
  }

  public void setDueDate(Date dueDate) {
    this.dueDate = dueDate;
  }

  public Invoice value(Float value) {
    this.value = value;
    return this;
  }

  /**
   * Invoice value
   * @return value
   **/
  @JsonProperty("value")
  @ApiModelProperty(value = "Invoice value")
  public Float getValue() {
    return value;
  }

  public void setValue(Float value) {
    this.value = value;
  }

  public Invoice contractNumber(String contractNumber) {
    this.contractNumber = contractNumber;
    return this;
  }

  /**
   * Contract number
   * @return contractNumber
   **/
  @JsonProperty("contractNumber")
  @ApiModelProperty(value = "Contract number")
  public String getContractNumber() {
    return contractNumber;
  }

  public void setContractNumber(String contractNumber) {
    this.contractNumber = contractNumber;
  }

  public Invoice nfeNumber(String nfeNumber) {
    this.nfeNumber = nfeNumber;
    return this;
  }

  /**
   * NF-e number
   * @return nfeNumber
   **/
  @JsonProperty("nfeNumber")
  @ApiModelProperty(value = "NF-e number")
  public String getNfeNumber() {
    return nfeNumber;
  }

  public void setNfeNumber(String nfeNumber) {
    this.nfeNumber = nfeNumber;
  }

  public Invoice status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Invoice status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "Invoice status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Invoice emissionDate(Date emissionDate) {
    this.emissionDate = emissionDate;
    return this;
  }

  /**
   * Invoice emission date
   * @return emissionDate
   **/
  @JsonProperty("emissionDate")
  @ApiModelProperty(value = "Invoice emission date")
  public Date getEmissionDate() {
    return emissionDate;
  }

  public void setEmissionDate(Date emissionDate) {
    this.emissionDate = emissionDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Invoice invoice = (Invoice) o;
    return Objects.equals(this.dueDate, invoice.dueDate) &&
        Objects.equals(this.value, invoice.value) &&
        Objects.equals(this.contractNumber, invoice.contractNumber) &&
        Objects.equals(this.nfeNumber, invoice.nfeNumber) &&
        Objects.equals(this.status, invoice.status) &&
        Objects.equals(this.emissionDate, invoice.emissionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dueDate, value, contractNumber, nfeNumber, status, emissionDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Invoice {\n");
    
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    contractNumber: ").append(toIndentedString(contractNumber)).append("\n");
    sb.append("    nfeNumber: ").append(toIndentedString(nfeNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    emissionDate: ").append(toIndentedString(emissionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

