/*
 * Menu API
 * This Menu API allows you to obtain the menu links and names
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CorporateSystemsSaoCarlos@br.experian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.serasa.common.utils.model.athenas;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * The menu item information
 */
@ApiModel(description = "The menu item information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-30T15:30:58.385-03:00")
public class MenuItem   {
  @JsonProperty("item")
  private String item = null;

  @JsonProperty("link")
  private String link = null;

  public MenuItem item(String item) {
    this.item = item;
    return this;
  }

  /**
   * The menu item name
   * @return item
   **/
  @JsonProperty("item")
  @ApiModelProperty(value = "The menu item name")
  public String getItem() {
    return item;
  }

  public void setItem(String item) {
    this.item = item;
  }

  public MenuItem link(String link) {
    this.link = link;
    return this;
  }

  /**
   * The menu item link
   * @return link
   **/
  @JsonProperty("link")
  @ApiModelProperty(value = "The menu item link")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuItem menuItem = (MenuItem) o;
    return Objects.equals(this.item, menuItem.item) &&
        Objects.equals(this.link, menuItem.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(item, link);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuItem {\n");
    
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

