/*
 * Contract API
 * The Contract API allows you to select contract data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CorporateSystemsSaoCarlos@br.experian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.serasa.common.utils.model.athenas;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Contract VCM value
 */
@ApiModel(description = "Contract VCM value")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-14T11:18:49.952-03:00")
public class VCMValue   {
  @JsonProperty("vcmValue")
  private Float vcmValue = null;

  public VCMValue vcmValue(Float vcmValue) {
    this.vcmValue = vcmValue;
    return this;
  }

  /**
   * Contract VCM value
   * @return vcmValue
   **/
  @JsonProperty("vcmValue")
  @ApiModelProperty(value = "Contract VCM value")
  public Float getVcmValue() {
    return vcmValue;
  }

  public void setVcmValue(Float vcmValue) {
    this.vcmValue = vcmValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VCMValue vcMValue = (VCMValue) o;
    return Objects.equals(this.vcmValue, vcMValue.vcmValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vcmValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VCMValue {\n");
    
    sb.append("    vcmValue: ").append(toIndentedString(vcmValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

